# Generated by Django 4.1.7 on 2023-04-03 15:50

from django.db import migrations
from django.core.management import call_command

def load_initial_data(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    call_command('loaddata','initial_data',
        database=db_alias,
        app_label='messenger',
    )

class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_initial_data),
    ]
